#!/bin/env ruby
require 'rdf/cli/vocab-loader'

# For example: ```bundle exec scripts/voc-file --source path.ttl --prefix
# http://judsonlester.info/rdf-vocab/path# --class-name
# "RoadForest::Vocab::Path"```

loader = RDF::VocabularyLoader.new
loader.go(ARGV)
